Repository wardenenv/warden, pull requests merged in 2020-04, with the labels that each got.

#139 Rollback `tmpfs` to `tmp` paths of tests
  CHANGELOG.md
  environments/magento2/magento2.tests.yml
Labels: bug

#141 Use Mutagen pause/resume on stopped environments
  CHANGELOG.md
  commands/env.cmd
  commands/sync.cmd
  commands/sync.help
Labels: enhancement

#142 Change large file exclude by type to per session ignore support
  CHANGELOG.md
  commands/env-init.cmd
  commands/sync.cmd
  docs/environments/initializing.md
  environments/magento2/magento2.mutagen.yml
Labels: bug, enhancement
