Repository wardenenv/warden, pull requests merged in 2022-02, with the labels that each got.

#458 Add `traefik.docker.network` label to specify docker network exclusively
  environments/includes/allure.base.yml
  environments/includes/elasticsearch.base.yml
  environments/includes/nginx.base.yml
  environments/includes/rabbitmq.base.yml
  environments/includes/varnish.base.yml
  environments/magento2/magento2.base.yml
Labels: enhancement

#487 Fix homepage logo
  homepage/src/html/index.html
Labels: bug

#491 Fix gulp-sass 5 does not have a default Sass compiler error
  homepage/gulpfile.js
  homepage/package-lock.json
  homepage/package.json
Labels: documentation
